name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set JDK environment variables
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64" >> $GITHUB_ENV
        echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Set SDK directory in local.properties
      run: echo 'sdk.dir=$ANDROID_HOME' > local.properties
      
    - name: Define alias for gradlew
      run: alias gradlew='JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64 bash ./gradlew'

    - name: Build with Gradle
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks
        export STORE_PASSWORD="${{ secrets.STORE_PASSWORD }}"
        export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
        export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
        ls
        gradlew assembleRelease        
      
    - name: Archive artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: Release APK
        path: app/build/outputs/apk/release/*.apk
