version: 2
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: mobiledevops/android-sdk-image:33.0.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Android
        run: |
          chmod +x gradlew
          ./gradlew clean assembleRelease
